"""Add soil type to farm conditions

Revision ID: bbfc6c0997e9
Revises: dee8b2695c87
Create Date: 2026-08-16 15:21:44.519715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbfc6c0997e9'
down_revision: Union[str, Sequence[str], None] = 'dee8b2695c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm_conditions', sa.Column('soil_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farm_conditions', 'soil_type')
    # ### end Alembic commands ###
