"""create crop monitoring

Revision ID: d9fd2e4de896
Revises: f8413a44bd33
Create Date: 2026-08-15 14:57:12.608542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9fd2e4de896'
down_revision: Union[str, Sequence[str], None] = 'f8413a44bd33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_monitoring',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('monitoring_date', sa.Date(), nullable=False),
    sa.Column('growth_stage', sa.String(length=100), nullable=False),
    sa.Column('plant_height', sa.Float(), nullable=True),
    sa.Column('crop_health', sa.String(length=50), nullable=True),
    sa.Column('pest_observed', sa.Boolean(), nullable=False),
    sa.Column('disease_observed', sa.Boolean(), nullable=False),
    sa.Column('observation_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_monitoring_crop_id'), 'crop_monitoring', ['crop_id'], unique=False)
    op.create_index(op.f('ix_crop_monitoring_id'), 'crop_monitoring', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crop_monitoring_id'), table_name='crop_monitoring')
    op.drop_index(op.f('ix_crop_monitoring_crop_id'), table_name='crop_monitoring')
    op.drop_table('crop_monitoring')
    # ### end Alembic commands ###
