"""create disease detections

Revision ID: f8413a44bd33
Revises: f9835b5e7542
Create Date: 2026-08-15 11:06:16.194741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8413a44bd33'
down_revision: Union[str, Sequence[str], None] = 'f9835b5e7542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disease_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('disease_name', sa.String(length=150), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('recommended_treatment', sa.Text(), nullable=True),
    sa.Column('preventive_measures', sa.Text(), nullable=True),
    sa.Column('detection_source', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disease_detections_crop_id'), 'disease_detections', ['crop_id'], unique=False)
    op.create_index(op.f('ix_disease_detections_disease_name'), 'disease_detections', ['disease_name'], unique=False)
    op.create_index(op.f('ix_disease_detections_farm_id'), 'disease_detections', ['farm_id'], unique=False)
    op.create_index(op.f('ix_disease_detections_id'), 'disease_detections', ['id'], unique=False)
    op.create_index(op.f('ix_disease_detections_severity'), 'disease_detections', ['severity'], unique=False)
    op.create_index(op.f('ix_disease_detections_status'), 'disease_detections', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disease_detections_status'), table_name='disease_detections')
    op.drop_index(op.f('ix_disease_detections_severity'), table_name='disease_detections')
    op.drop_index(op.f('ix_disease_detections_id'), table_name='disease_detections')
    op.drop_index(op.f('ix_disease_detections_farm_id'), table_name='disease_detections')
    op.drop_index(op.f('ix_disease_detections_disease_name'), table_name='disease_detections')
    op.drop_index(op.f('ix_disease_detections_crop_id'), table_name='disease_detections')
    op.drop_table('disease_detections')
    # ### end Alembic commands ###
