"""create crop advisories

Revision ID: f9835b5e7542
Revises: 359cf4ba3211
Create Date: 2026-08-14 22:12:53.139457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9835b5e7542'
down_revision: Union[str, Sequence[str], None] = '359cf4ba3211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_advisories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('advisory_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_advisories_advisory_type'), 'crop_advisories', ['advisory_type'], unique=False)
    op.create_index(op.f('ix_crop_advisories_crop_id'), 'crop_advisories', ['crop_id'], unique=False)
    op.create_index(op.f('ix_crop_advisories_farm_id'), 'crop_advisories', ['farm_id'], unique=False)
    op.create_index(op.f('ix_crop_advisories_id'), 'crop_advisories', ['id'], unique=False)
    op.create_index(op.f('ix_crop_advisories_priority'), 'crop_advisories', ['priority'], unique=False)
    op.create_index(op.f('ix_crop_advisories_status'), 'crop_advisories', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crop_advisories_status'), table_name='crop_advisories')
    op.drop_index(op.f('ix_crop_advisories_priority'), table_name='crop_advisories')
    op.drop_index(op.f('ix_crop_advisories_id'), table_name='crop_advisories')
    op.drop_index(op.f('ix_crop_advisories_farm_id'), table_name='crop_advisories')
    op.drop_index(op.f('ix_crop_advisories_crop_id'), table_name='crop_advisories')
    op.drop_index(op.f('ix_crop_advisories_advisory_type'), table_name='crop_advisories')
    op.drop_table('crop_advisories')
    # ### end Alembic commands ###
